name: magic_home
description: A library that imports functionality from the Magic Home app, allowing control of smart lights.
version: 1.0.0
homepage: https://github.com/nathanielxd/

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
